solidus/backend/config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    put '/locale/set', to: 'locale#set', defaults: { format: :json }, as: :set_locale

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
      resources :promotion_code_batches, only: [:index, :new, :create] do
        get '/download', to: "promotion_code_batches#download", defaults: { format: "csv" }
      end
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        post :clone
      end
      resources :variants, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: :edit
    resources :stores, only: [:index, :new, :create, :edit, :update]

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_locations do
      resources :stock_movements, only: [:index]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

solidus/backend/app/controllers/spree/admin/stores_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class StoresController < Spree::Admin::ResourceController
      def index
        if Spree::Store.count == 1
          redirect_to edit_admin_store_path(Spree::Store.first)
        else
          @stores = Spree::Store.all
        end
      end

      private

      def store_params
        params.require(:store).permit(permitted_params)
      end

      def permitted_params
        Spree::PermittedAttributes.store_attributes
      end
    end
  end
end

solidus/backend/app/views/spree/admin/stores/_form.html.erb
<div class="row">
  <div class="col-12 col-md-6">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required' %>
      <%= f.text_field :name, required: true, class: 'fullwidth' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :code do %>
      <%= f.label :code, class: 'required' %>
      <%= f.text_field :code, required: true, class: 'fullwidth' %>
      <%= f.error_message_on :code %>
    <% end %>

    <%= f.field_container :seo_title do %>
      <%= f.label :seo_title %>
      <%= f.text_field :seo_title, class: 'fullwidth'  %>
      <%= f.error_message_on :seo_title %>
    <% end %>

    <%= f.field_container :meta_keywords do %>
      <%= f.label :meta_keywords %>
      <%= f.text_field :meta_keywords, class: 'fullwidth'  %>
      <%= f.error_message_on :meta_keywords %>
    <% end %>

    <%= f.field_container :meta_description do %>
      <%= f.label :meta_description %>
      <%= f.text_area :meta_description, class: 'fullwidth'  %>
      <%= f.error_message_on :meta_description %>
    <% end %>
  </div>
  <div class="col-12 col-md-6">
    <%= f.field_container :url do %>
      <%= f.label :url, class: 'required' %>
      <%= f.text_field :url, required: true, class: 'fullwidth'  %>
      <%= f.error_message_on :url %>
    <% end %>

    <%= f.field_container :mail_from_address do %>
      <%= f.label :mail_from_address, class: 'required' %>
      <%= f.text_field :mail_from_address, required: true, class: 'fullwidth'  %>
      <%= f.error_message_on :mail_from_address %>
    <% end %>

    <%= f.field_container :default_currency do %>
      <%= f.label :default_currency %>
      <%= f.select :default_currency,
        Spree::Config.available_currencies.map(&:iso_code),
        { include_blank: true },
        { class: 'custom-select fullwidth' } %>
      <%= f.error_message_on :default_currency %>
    <% end %>

    <%= f.field_container :cart_tax_country_iso do %>
      <%= f.label :cart_tax_country_iso %>
      <%= f.field_hint :cart_tax_country_iso %>
      <%= f.select :cart_tax_country_iso,
        Spree::Country.all.map { |c| [c.name, c.iso] },
        { include_blank: t(".no_cart_tax_country") },
        { class: "custom-select fullwidth" } %>
      <%= f.error_message_on :cart_tax_country_iso %>
    <% end %>

    <%= f.field_container :available_locales do %>
      <%= f.label :available_locales %>
      <%= f.field_hint :available_locales %>
      <%= f.select :available_locales,
        Spree.i18n_available_locales.map { |locale|
          [I18n.t('spree.i18n.this_file_language', locale: locale, default: locale.to_s, fallback: false), locale]
        }.sort,
        { },
        { class: 'select2 fullwidth', multiple: true } %>
      <%= f.error_message_on :default_currency %>
    <% end %>
  </div>
</div>

solidus/backend/app/views/spree/admin/stores/edit.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% admin_breadcrumb(link_to(plural_resource_name(Spree::Store), admin_stores_path)) %>
<% admin_breadcrumb(@store.name) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.new_store'), new_admin_store_url, class: 'btn btn-primary' %>
  </li>
<% end %>

<%= form_for [:admin, @store] do |f| %>
  <fieldset class="no-border-top">
    <%= render 'form', f: f %>
    <% if can? :update, @store %>
      <%= render 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </fieldset>
<% end %>

solidus/backend/app/views/spree/admin/stores/index.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Store) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Store) %>
    <li>
      <%= link_to t('spree.new_store'), new_admin_store_url, class: 'button' %>
    </li>
  <% end %>
<% end %>

<table class="index">
  <thead>
    <tr>
      <th><%= Spree::Store.human_attribute_name(:name) %></th>
      <th><%= Spree::Store.human_attribute_name(:url) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td>
          <%= store.name %>
          <% if store.default? %>
            <span class="label label-default"><%= Spree::Store.human_attribute_name(:default) %></span>
          <% end %>
        </td>
        <td><%= store.url %></td>
        <td class="actions">
          <% if can?(:edit, store) %>
            <%= link_to_edit store, no_text: true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

solidus/backend/app/views/spree/admin/stores/new.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% admin_breadcrumb(link_to(plural_resource_name(Spree::Store), admin_stores_path)) %>
<% admin_breadcrumb(t('spree.new_store')) %>

<% content_for :page_actions do %>
<% end %>

<%= form_for [:admin, @store] do |f| %>
  <%= render 'form', f: f %>

  <% if can? :create, @store %>
    <%= render 'spree/admin/shared/new_resource_links' %>
  <% end %>
<% end %>