solidus/backend/config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    put '/locale/set', to: 'locale#set', defaults: { format: :json }, as: :set_locale

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
      resources :promotion_code_batches, only: [:index, :new, :create] do
        get '/download', to: "promotion_code_batches#download", defaults: { format: "csv" }
      end
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        post :clone
      end
      resources :variants, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: :edit
    resources :stores, only: [:index, :new, :create, :edit, :update]

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_locations do
      resources :stock_movements, only: [:index]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

solidus/backend/app/controllers/spree/admin/option_types_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class OptionTypesController < ResourceController
      before_action :setup_new_option_value, only: :edit

      def update_values_positions
        params[:positions].each do |id, index|
          Spree::OptionValue.where(id: id).update_all(position: index)
        end

        respond_to do |format|
          format.js { head :no_content }
        end
      end

      private

      def location_after_save
        edit_admin_option_type_url(@option_type)
      end

      def load_product
        @product = Spree::Product.find_by_param!(params[:product_id])
      end

      def setup_new_option_value
        @option_type.option_values.build if @option_type.option_values.empty?
      end

      def set_available_option_types
        @available_option_types = if @product.option_type_ids.any?
          Spree::OptionType.where('id NOT IN (?)', @product.option_type_ids)
        else
          Spree::OptionType.all
        end
      end
    end
  end
end

solidus/backend/app/views/spree/admin/option_types/_form.html.erb
<div data-hook="admin_option_type_form_fields" class="align-center row">
  <div class="col-6">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required' %><br />
      <%= f.text_field :name, class: "fullwidth" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="col-6">
    <%= f.field_container :presentation do %>
      <%= f.label :presentation, class: 'required' %><br />
      <%= f.text_field :presentation, class: "fullwidth" %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
</div>

solidus/backend/app/views/spree/admin/option_types/_option_value_fields.html.erb
<tr class="option_value fields" id="spree_<%= dom_id(f.object) %>"  data-hook="option_value">
  <td>
    <% if f.object.persisted? %>
      <span class="handle"></span>
      <%= f.hidden_field :id %>
    <% end %>
  </td>
  <td class="name"><%= f.text_field :name %></td>
  <td class="presentation"><%= f.text_field :presentation %></td>
  <td class="actions"><%= link_to_remove_fields t('spree.actions.remove'), f, no_text: true %></td>
</tr>

solidus/backend/app/views/spree/admin/option_types/edit.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::OptionType), spree.admin_option_types_path) %>
<% admin_breadcrumb(@option_type.name) %>


<% content_for :page_actions do %>
  <li>
    <span id="new_add_option_value" data-hook>
      <%= link_to_add_fields t('spree.add_option_value'), "tbody#option_values", class: 'button' %>
    </span>
  </li>
  <% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @option_type } %>

<%= form_for [:admin, @option_type] do |f| %>

  <fieldset class="no-border-bottom">
    <legend><%= Spree::OptionType.model_name.human %></legend>
    <%= render partial: 'form', locals: { f: f } %>
  </fieldset>

  <fieldset>
    <legend><%= plural_resource_name(Spree::OptionValue) %></legend>
    <table class="index sortable" data-hook data-sortable-link="<%= update_values_positions_admin_option_types_url %>">
      <thead data-hook="option_header">
        <tr>
          <th></th>
          <th><%= Spree::OptionValue.human_attribute_name(:name) %></th>
          <th><%= Spree::OptionValue.human_attribute_name(:presentation) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="option_values">
        <%= f.fields_for :option_values, @option_values do |option_value_form| %>
          <%= render partial: 'option_value_fields', locals: { f: option_value_form } %>
        <% end %>
      </tbody>
    </table>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

solidus/backend/app/views/spree/admin/option_types/index.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(plural_resource_name(Spree::OptionType)) %>


<% content_for :page_actions do %>
  <% if can?(:create, Spree::OptionType) %>
    <li id="new_ot_link">
      <%= link_to t('spree.new_option_type'), new_admin_option_type_url, remote: true, id: 'new_option_type_link', class: 'btn btn-primary' %>
    </li>
  <% end %>
<% end %>

<div id="new_option_type"></div>

<% if @option_types.any? %>
<table class="index sortable" id="listing_option_types" data-hook data-sortable-link="<%= update_positions_admin_option_types_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 35%">
    <col style="width: 40%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th></th>
      <th><%= Spree::OptionType.human_attribute_name(:name) %></th>
      <th><%= Spree::OptionType.human_attribute_name(:presentation) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @option_types.each do |option_type| %>
      <tr class="spree_option_type" id="<%= spree_dom_id option_type %>" data-hook="option_row">
        <td><span class="handle"></span></td>
        <td><%= option_type.name %></td>
        <td class="presentation"><%= option_type.presentation %></td>
        <td class="actions">
          <% if can?(:update, option_type) %>
            <%= link_to_edit(option_type, class: 'admin_edit_option_type', no_text: true) %>
          <% end %>
          <% if can?(:destroy, option_type) %>
            <%= link_to_delete(option_type, no_text: true) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::OptionType,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

solidus/backend/app/views/spree/admin/option_types/new.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @option_type } %>

<%= form_for [:admin, @option_type] do |f| %>
  <fieldset>
    <legend align="center"><%= t('spree.new_option_type') %></legend>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

solidus/backend/app/views/spree/admin/option_types/new.js.erb
$("#new_option_type").html('<%= escape_javascript(render template: "spree/admin/option_types/new", formats: [:html], handlers: [:erb]) %>');
$("#new_option_type_link").parent().hide();